[package]
name = "auto-diff"
version = "0.1.0"
authors = ["yguan <yguan@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"

[dev-dependencies]
criterion = "0.3"

[features]

[[bench]]
name = "my_benchmark"
harness = false
